require("config.globals")
require("config.settings")
require("config.mappings")
require("config.lazy")
require("config.aucmds")

-- vim.cmd("colorscheme rvcs")
-- vim.cmd("colorscheme base16-classic-dark")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme sonokai")
-- vim.cmd("colorscheme darkplus")
-- vim.cmd("colorscheme vscode")
-- vim.cmd("colorscheme oxocarbon")
-- require("config.colorscheme")

-- vim.api.nvim_set_keymap('n', '<Leader>dl', ":lua require('config.dbg.ruby').launch()<CR>", {})
