local c = require("sigma.colors")
local u = require("sigma.util")

return {
    DAPBreakpointLine            = { bg = u.darken(c.severity.error, 0.45) },
    DAPLogpointLine              = { bg = u.darken(c.overlay.fg, 0.85) },
    DAPBreakpointConditionalLine = { bg = u.darken(c.severity.warning, 0.45) },
    DAPBreakpointRejectedLine    = { underdashed = true, sp = c.severity.error },
    DAPBreakpointDisabledLine    = { underdashed = true, sp = c.severity.hint },

    DAPFrameStopLine             = { bg = u.darken(c.boolean, 0.45) },
    DAPFrameStopVirtText         = { fg = c.boolean },
    DAPFocusedFrameLine          = { underline = true, sp = c.boolean },

    -- Legacy:
    -- DapBreakpoint                = { fg = c.severity.error },
    -- DapBreakpointLine            = { bg = u.darken(c.severity.error, 0.45) },
    -- DapBreakpointCondition       = { fg = c.severity.warning },
    -- DapBreakpointConditionLine   = { bg = u.darken(c.severity.warning, 0.45) },
    -- DapBreakpointRejected        = { fg = c.severity.error },
    -- DapBreakpointRejectedLine    = { underdashed = true, sp = c.severity.error },
    -- DapLogPoint                  = { fg = c.severity.info },
    -- DapLogPointLine              = { bg = u.darken(c.overlay.fg, 0.85) },
    -- DapStopped                   = { fg = c.severity.hint },
    -- DapStoppedLine               = { bg = u.darken(c.boolean, 0.45), underline = true, sp = c.boolean },

    -- DapUINormal                  = { link = "NormalFloat" },
    -- DapUIVariable                = { link = "@variable" },
    -- DapUIScope                   = { fg = c.overlay.accentDark },
    -- DapUIType                    = { link = "@type" },
    -- DapUIValue                   = { fg = c.fg },
    -- DapUIModifiedValue           = { fg = c.overlay.accentDark, bold = true },
    -- DapUIDecoration              = { fg = c.overlay.accentDark },
    -- DapUIThread                  = { fg = c.boolean },
    -- DapUIStoppedThread           = { fg = c.overlay.accentDark },
    -- DapUIFrameName               = { fg = c.fg },
    -- DapUISource                  = { fg = c.boolean },
    -- DapUILineNumber              = { link = "LineNr" },
    -- DapUIFloatNormal             = { link = "NormalFloat" },
    -- DapUIFloatBorder             = { link = "FloatBorder" },
    -- DapUIWatchesEmpty            = { fg = c.comment },
    -- DapUIWatchesValue            = { fg = c.proc },
    -- DapUIWatchesError            = { fg = c.keyword },
    -- DapUIBreakpointsPath         = { fg = c.boolean },
    -- DapUIBreakpointsInfo         = { fg = c.proc },
    -- DapUIBreakpointsCurrentLine  = { link = "UNSET" },
    -- DapUIBreakpointsLine         = { link = "CursorLineNr" },
    -- DapUIBreakpointsDisabledLine = { link = "UNSET" },
    -- DapUICurrentFrameName        = { link = "DapUIBreakpointsCurrentLine" },
    -- DapUIStepOver                = { fg = c.overlay.accentDark },
    -- DapUIStepInto                = { fg = c.overlay.accentDark },
    -- DapUIStepBack                = { fg = c.overlay.accentDark },
    -- DapUIStepOut                 = { fg = c.overlay.accentDark },
    -- DapUIStop                    = { fg = c.keyword },
    -- DapUIPlayPause               = { fg = c.proc },
    -- DapUIRestart                 = { fg = c.proc },
    -- DapUIUnavailable             = { link = "UNSET" },
    -- DapUIWinSelect               = { fg = c.overlay.accentDark },
    -- DapUIEndofBuffer             = { link = "EndofBuffer" },
}
