local c = require("sigma.colors")

return {
    ["@lsp.kind.class"] = { link = "@lsp.type.class" },
    ["@lsp.kind.color"] = { link = "Pmenu" },
    ["@lsp.kind.constant"] = { link = "@constant" },
    ["@lsp.kind.constructor"] = { link = "@constructor" },
    ["@lsp.kind.enum"] = { link = "@lsp.type.enum" },
    ["@lsp.kind.enumMember"] = { link = "@lsp.type.enumMember" },
    ["@lsp.kind.event"] = { link = "@lsp.type.event" },
    ["@lsp.kind.field"] = { link = "@lsp.type.property" },
    ["@lsp.kind.file"] = { fg = c.bg, bg = c.orange },
    ["@lsp.kind.folder"] = { link = "@lsp.kind.file" },
    ["@lsp.kind.function"] = { link = "@lsp.type.function" },
    ["@lsp.kind.interface"] = { link = "@lsp.type.interface" },
    ["@lsp.kind.keyword"] = { link = "@lsp.type.keyword" },
    ["@lsp.kind.method"] = { link = "@lsp.type.method" },
    ["@lsp.kind.module"] = { link = "@lsp.type.namespace" },
    ["@lsp.kind.operator"] = { link = "@lsp.type.operator" },
    ["@lsp.kind.property"] = { link = "@lsp.type.property" },
    ["@lsp.kind.reference"] = { link = "Normal" },
    ["@lsp.kind.snippet"] = { link = "Comment" },
    ["@lsp.kind.struct"] = { link = "@lsp.type.struct" },
    ["@lsp.kind.text"] = { link = "Normal" },
    ["@lsp.kind.typeParameter"] = { link = "@lsp.type.typeParameter" },
    ["@lsp.kind.unit"] = { link = "@number" },
    ["@lsp.kind.value"] = { link = "Normal" },
    ["@lsp.kind.variable"] = { link = "@lsp.type.variable" },
}
